-- Nexpert Trust System Schema Migration

-- 1. Trust Events Table (Captures raw events from the PHP system)
CREATE TABLE IF NOT EXISTS `trust_events` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `event_type` ENUM('session_completed', 'booking_created', 'feedback_submitted', 'expert_profile_updated', 'kyc_verified', 'complaint_logged') NOT NULL,
  `expert_id` INT NOT NULL,
  `learner_id` INT DEFAULT NULL,
  `payload` JSON DEFAULT NULL,
  `status` ENUM('pending', 'processing', 'processed', 'failed') DEFAULT 'pending',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX (`expert_id`),
  INDEX (`event_type`),
  INDEX (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2. Trust Signals Table (Structured signals generated by agents)
CREATE TABLE IF NOT EXISTS `trust_signals` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `event_id` INT DEFAULT NULL,
  `expert_id` INT NOT NULL,
  `agent_type` ENUM('structure', 'outcome', 'boundary', 'consistency', 'audit') NOT NULL,
  `signal_value` DECIMAL(5,2) NOT NULL, -- 0.00 to 100.00
  `metadata` JSON DEFAULT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`event_id`) REFERENCES `trust_events`(`id`) ON DELETE SET NULL,
  INDEX (`expert_id`),
  INDEX (`agent_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 3. Trust State Table (Current state of trust for each expert)
CREATE TABLE IF NOT EXISTS `trust_state` (
  `expert_id` INT PRIMARY KEY,
  `overall_score` DECIMAL(5,2) DEFAULT 0.00,
  `trust_tier` ENUM('A', 'B', 'C') DEFAULT 'C',
  `stability_score` DECIMAL(5,2) DEFAULT 0.00,
  `structure_score` DECIMAL(5,2) DEFAULT 0.00,
  `outcome_score` DECIMAL(5,2) DEFAULT 0.00,
  `boundary_score` DECIMAL(5,2) DEFAULT 0.00,
  `consistency_score` DECIMAL(5,2) DEFAULT 0.00,
  `last_updated` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (`expert_id`) REFERENCES `users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 4. Trust State History (Historical snapshots for timeline)
CREATE TABLE IF NOT EXISTS `trust_state_history` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `expert_id` INT NOT NULL,
  `overall_score` DECIMAL(5,2) NOT NULL,
  `trust_tier` ENUM('A', 'B', 'C') NOT NULL,
  `stability_score` DECIMAL(5,2) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX (`expert_id`),
  INDEX (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
